# Generated by Django 6.0.3 on 2026-03-19 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilaReproducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('dias_semana', models.JSONField(blank=True, help_text='Ex: [0,1,2]', null=True)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilaPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='ads.filareproducao')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistMidia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='playlists/')),
                ('tipo', models.CharField(editable=False, max_length=10)),
                ('ordem', models.PositiveIntegerField()),
                ('duracao', models.PositiveIntegerField(blank=True, help_text='Tempo em segundos (somente imagem)', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='ads.playlist')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
